/**
 * Every `var(--token)` this site uses must actually be defined.
 *
 * WHY THIS EXISTS. `background: var(--color-surface)` where `--color-surface`
 * is undefined is not an error and not a warning: the declaration is simply
 * DROPPED, and the element keeps whatever background it would otherwise have
 * had. Measured 2026-09-05, every event card on the marketplace had been
 * TRANSPARENT since Tab 03 - sitting directly on the page tint instead of the
 * white surface it was written to have - and it looked deliberate. The token
 * was `--color-surface`; the one that exists is `--color-surface-raised`.
 *
 * The same file had `var(--color-focus, currentColor)`, where the fallback made
 * the failure quieter still: the focus indicator rendered in the text colour on
 * every card, differing from every other focus ring on the site, and nothing
 * anywhere reported it. A FALLBACK TURNS A MISSING TOKEN INTO A DIFFERENT
 * DESIGN rather than a visible break, so a fallback is not an excuse from this
 * check - it is a reason for it.
 *
 * This is the [[gate-measures-its-own-output]] question asked of CSS: reading
 * the stylesheet can only ever prove the rule was WRITTEN. The companion
 * browser assertion, which proves the card is actually painted, lives in the
 * review suite; this one is cheap enough to run on every commit and names the
 * exact token, which a screenshot never can.
 */
import { readFileSync } from 'node:fs';
import { globSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

/** `var(--name` — the fallback, if any, is deliberately ignored. */
const USES = /var\(\s*(--[A-Za-z0-9-]+)/g;
/**
 * `--name:` at the start of a declaration.
 *
 * A backtick and a quote count as a boundary too, because a component may set a
 * property in an inline `style={`--ratio:${n}`}` - a real definition that a
 * stylesheet-only pattern would miss, reporting a false break on working code.
 */
const DEFINES = /(^|[;{`'"\s])(--[A-Za-z0-9-]+)\s*:/g;

const FILES = [...globSync('src/**/*.css'), ...globSync('src/**/*.astro')];

/**
 * Properties set from JavaScript or by the browser rather than in a stylesheet.
 *
 * Each needs a REASON, not just an entry. An exemption list nobody has to
 * justify is how a real miss gets waved through.
 */
const SET_ELSEWHERE = new Map<string, string>([
  // Written by scripts/motion.ts onto elements as an inline style.
  ['--enter-delay', 'set inline by the stagger in scripts/motion.ts'],
  ['--enter-duration', 'set inline by scripts/motion.ts'],
  ['--reveal-delay', 'set inline by scripts/motion.ts'],
  /*
   * LogoLockup builds these NAMES programmatically - `sizeVars('lg', width)`
   * emits `--lg-w`, `--lg-ml` and the rest into the element's inline style - so
   * no literal `--lg-w:` appears anywhere to find. This is the one shape a
   * textual scan genuinely cannot see, which is why it is listed rather than
   * pattern-matched.
   */
  ...(['xs', 'sm', 'md', 'lg'] as const).flatMap((tier) =>
    (['w', 'h', 'ml', 'mt', 'mr', 'mb'] as const).map(
      (axis) =>
        [`--${tier}-${axis}`, 'generated by sizeVars() into LogoLockup inline style'] as const,
    ),
  ),
]);

function collect(pattern: RegExp, text: string, group: number): string[] {
  const out: string[] = [];
  const re = new RegExp(pattern.source, pattern.flags);
  let match: RegExpExecArray | null = re.exec(text);
  while (match !== null) {
    const value = match[group];
    if (value) out.push(value);
    match = re.exec(text);
  }
  return out;
}

describe('every CSS custom property that is used is also defined', () => {
  it('finds source to scan', () => {
    /*
     * A glob that matches nothing produces an empty loop and a green test,
     * which is the failure this whole file is about.
     */
    expect(
      FILES.length,
      'no CSS or component files found; this test measures nothing',
    ).toBeGreaterThan(50);
  });

  it('defines every token it references', () => {
    const defined = new Set<string>(SET_ELSEWHERE.keys());
    const used = new Map<string, string[]>();

    for (const file of FILES) {
      const text = readFileSync(file, 'utf8');
      for (const name of collect(DEFINES, text, 2)) defined.add(name);
      for (const name of collect(USES, text, 1)) {
        used.set(name, [...(used.get(name) ?? []), file]);
      }
    }

    // The paired positive: the scan must actually see real tokens.
    expect(defined.size, 'no custom property definitions found').toBeGreaterThan(20);
    expect(used.size, 'no custom property uses found').toBeGreaterThan(20);

    const missing = [...used.entries()]
      .filter(([name]) => !defined.has(name))
      .map(([name, files]) => `${name} (used in ${[...new Set(files)].join(', ')})`);

    expect(missing, 'CSS custom properties that are used but never defined').toEqual([]);
  });
});
