#!/usr/bin/env node
/**
 * Generate docs/PENDING.md from src/config/pending.ts.
 *
 * The register is generated because eight tabs of hand-edits silently did
 * nothing: every edit was a literal patch against a Markdown table that
 * Prettier keeps re-padding, so the anchors stopped matching and the register
 * sat frozen at its Tab 01 state while reporting itself current.
 *
 * Run with --check to verify the committed file matches, which is what the
 * test does.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DELIBERATE_OMISSIONS, FRONTEND_ITEMS, OWNER_ITEMS } from '../src/config/pending.ts';

const OUT = fileURLToPath(new URL('../docs/PENDING.md', import.meta.url));

const strike = (item) =>
  item.state === 'DONE' || item.state === 'RESOLVED' ? `~~${item.id}~~` : item.id;

const rows = (items) =>
  items
    .map((item) => `| ${strike(item)} | **${item.state}** | ${item.item} | ${item.reason} |`)
    .join('\n');

const doc = `# Pending register

**Generated from \`src/config/pending.ts\` — do not edit this file by hand.**
Run \`npm run pending:write\` after changing the source; \`npm run test\` fails if
the two disagree.

Every unfinished item, with its reason and its owner.

States: **BLOCKED** (names what would unblock it) · **OWNER DECISION** (silence
is not approval) · **NOT REACHED** (queued, with the reason) · **IN PROGRESS** ·
**DONE** · **RESOLVED**.

## The id series in this repository

A prefix nobody declared is a prefix nobody can retire, and two of the four
below were being used without ever being written down. Every series this lane
allocates is listed here, with where it is defined and who closes it.

| Series | What it numbers | Defined in | Closed by |
| --- | --- | --- | --- |
| **F-#** | Front-end work | \`src/config/pending.ts\` (Part 1) | This lane |
| **B-#** | PAAIPE decisions and inputs | \`src/config/pending.ts\` (Part 2) | PAAIPE — silence is not approval |
| **A-#** | Front-end audit findings | \`docs/frontend-audit.md\` | This lane |
| **G-##** | Release-gate findings | \`docs/release-gate-limits.md\` | This lane |

Four rules, so an id means the same thing in a commit message, in this file and
in a message to another lane:

1. **Numbers are never reissued and never renumbered.** A gap is information —
   it says something was retired there. Renumbering would invalidate every
   cross-reference already committed, and a scheme that makes the archive wrong
   is abandoned within a week.
2. **Qualify at the boundary, not inside.** \`B-7\` stays \`B-7\` here. The moment
   it crosses into another lane's document or a bus message, write \`FE:B-7\` —
   the backend has its own \`Q-##\` and \`D-##\` series and "Q-02" is ambiguous the
   moment it leaves the repository that defines it.
3. **Zero-pad from the next new series forward**, never repad an existing one.
   That is rule 1.
4. **A retired id stays retired.** Reusing one makes every historical reference
   silently wrong, and it is the single mistake here that cannot be detected by
   reading the current state.

---

## Part 1 — Front end (F-#)

| id | State | Item | Reason |
| --- | --- | --- | --- |
${rows(FRONTEND_ITEMS)}

## Part 2 — PAAIPE decisions and inputs (B-#)

| id | State | Item | Reason |
| --- | --- | --- | --- |
${rows(OWNER_ITEMS)}

## Deliberately not done

Recorded so an omission is never read as an oversight.

${DELIBERATE_OMISSIONS.map((line) => `- ${line}`).join('\n')}
`;

if (process.argv.includes('--check')) {
  const current = await readFile(OUT, 'utf8').catch(() => '');
  // Compare on collapsed whitespace: Prettier reflows the table, and that is
  // exactly the reformatting that broke every hand-edit.
  const normalise = (text) => text.replace(/\s+/g, ' ').trim();
  if (normalise(current) !== normalise(doc)) {
    console.error('FAIL  docs/PENDING.md is out of date. Run: npm run pending:write');
    process.exit(1);
  }
  console.log('PASS  docs/PENDING.md matches src/config/pending.ts');
} else {
  await writeFile(OUT, doc);
  console.log(
    `Wrote docs/PENDING.md — ${FRONTEND_ITEMS.length} front-end items, ${OWNER_ITEMS.length} owner items, ${DELIBERATE_OMISSIONS.length} recorded omissions.`,
  );
}
